version: "3"

services:

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.11.8-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password


    cockroachdb:
        container_name: cockroachdb
        image: cockroachdb/cockroach:latest
        ports:
            - 26257:26257
            - 8080:8080
        command: start-single-node --insecure