version: "3"

services:

    rabbitmq:
        container_name: rabbitmq
        image: rabbitmq:3.11.8-management-alpine
        ports:
            - 5672:5672
            - 15672:15672
        environment:
            RABBITMQ_DEFAULT_USER: user
            RABBITMQ_DEFAULT_PASS: password


    cockroachdb:
        container_name: cockroachdb
        image: cockroachdb/cockroach:latest
        ports:
            - 26257:26257
            - 8080:8080
        command: start-single-node --insecure

    # database 0 is used by authentication microservice
    # database 1 is used by otp microservices
    redis:
        container_name: redis
        image: redis:7-alpine
        ports:
            - 6379:6379
        command: redis-server --requirepass password --databases 2
        environment:
            REDIS_REPLICATION_MODE: master
            REDIS_PORT: 6379
            WAIT_HOSTS: redis:6379
            REDIS_PASSWORD: password